draw_bold_text_with_bright_colors = true
background_opacity = 1
live_config_reload = false
working_directory = "None"
alt_send_esc = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = false
decorations = "full"
startup_mode = "Windowed"
dynamic_title = true

  [window.dimensions]
  columns = 80
  lines = 24

  [window.padding]
  x = 10
  y = 10

[scrolling]
history = 2_500
multiplier = 3

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = "Block"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = false

  [mouse.double_click]
  threshold = 300

  [mouse.triple_click]
  threshold = 300

[[mouse_bindings]]
mouse = "Middle"
action = "PasteSelection"

[[key_bindings]]
key = "Paste"
action = "Paste"

[[key_bindings]]
key = "Copy"
action = "Copy"

[[key_bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[key_bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[key_bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[key_bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[key_bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[key_bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[key_bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[key_bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[key_bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[key_bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[key_bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[key_bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[key_bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[key_bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[key_bindings]]
key = "NumpadAdd"
mods = "Control"
action = "IncreaseFontSize"

[[key_bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[key_bindings]]
key = "NumpadSubtract"
mods = "Control"
action = "DecreaseFontSize"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
